version: "2"

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    environment:
      REVERSE_PROXY_DOMAIN_NAME: ${REVERSE_PROXY_DOMAIN_NAME}
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: nginx

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "xpack.security.enabled=false"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    environment:
      SERVER_NAME: kibana

  logstash:
    build: logstash
    ports:
      - "12201:12201/udp"

volumes:
  elasticsearch-data:
    driver: local
